### ISSUE TITLE
I like rounded corners

### ISSUE THREAD

**Issue by hellotosamuel** [pacehub/pacehub#7]
for div id="map"

element.style {
    _**border-radius: 6px;**_
    height: 600px;
    width: 100%;
    position: relative;
    overflow: hidden;
    transform: translateZ(0px);
    background-color: rgb(229, 227, 223);
}

lets add border radius!

**Comment by eeshansim** [comment]
kk you know how to add?

**Comment by hellotosamuel** [comment]
Will try to figure it out once i log out of your github and do a successful pull..
